blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    text = models.TextField(verbose_name='Содержимое')
    blog_img = models.ImageField(upload_to='blog/', verbose_name='Превью', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, **NULLABLE, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return (f'Название: {self.title}'
                f'Дата создания: {self.created_at}'
                f'Опубликовано: {self.is_published}')

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'text', 'blog_img',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Создание'})
        return context


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'text', 'blog_img', 'is_published',)

    def form_valid(self, form):
        """
        Формирование slug
        """
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        """
        Переход на просмотр материала
        """
        return reverse('blog:view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Редактирование'})
        return context


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """
        Фильтр опубликованных материалов
        """
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Блог'})
        return context


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """
        Счетчик просмотров
        """
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        blog_item = Blog.objects.get(pk=self.kwargs.get('pk'))
        context_data['blog_pk'] = blog_item.pk,
        context_data['title'] = f'Статья - {blog_item.title}'

        return context_data


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Удаление'})
        return context

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load my_tags %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Статья "{{ object.title }}"
                                ({{ object.slug }})
                            </h3>
                        </div>
                        <img class="card-img-top d-flex h-100 p-3 mx-auto flex-column" src="{{ object.blog_img|mymedia }}" alt="blog_img" style="max-width: 50%;">
                        <div class="card-body">
                            <p>
                                {{ object.text }}
                            </p>
                        </div>
                        <div class="card-footer">
                            Просмотры: {{ object.views_count }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pb-md-4 mx-auto text-center">
    <p class="lead">Все наши статьи</p>
</div>
<div class="container">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
    </div>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ object.blog_img|mymedia }}" alt="blog_img">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.title }}</h2>
                </div>
                <div class="card-body">
                    <h6 class="card-title pricing-card-title">{{ object.created_at }}</h6>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.text|slice:100 }}</li>
                    </ul>
                    <a href="{% url 'blog:view' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">Читать</a>
                </div>
                <div class="btn-group">

                    <a href="{% url 'blog:update' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'blog:delete' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-danger">Удалить</a>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}