blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contact'),
    # path('product/', ProductListView.as_view(), name='products'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(max_length=250, **NULLABLE, verbose_name='Описание')
    image = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, **NULLABLE, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(**NULLABLE, verbose_name='Цена')
    created_at = models.DateField(**NULLABLE, verbose_name='Дата создания')
    updated_at = models.DateField(**NULLABLE, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f'{self.name} : {self.description}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.CharField(max_length=50, verbose_name='Номер версии', **NULLABLE)
    version_name = models.CharField(max_length=50, verbose_name='Название версии')
    is_active = models.BooleanField(verbose_name='Признак текущей версии', default=False)

    def __str__(self):
        return f'{self.version_number} - {self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():

            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        word_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in word_list:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError(f'Использование слова "{word}" в названии запрещено!')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        word_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in word_list:
            if word.lower() in cleaned_data.lower():
                raise forms.ValidationError(f'Использование слова "{word}" в описании продукта запрещено!')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView, View, CreateView, UpdateView, DeleteView
from django.forms import inlineformset_factory
from catalog.models import Product, Version
from django.urls import reverse_lazy, reverse
from catalog.forms import ProductForm, VersionForm


# class HomeView(TemplateView):
#     template_name = 'catalog/product_list.html'
#
#     def get_context_data(self, **kwargs):
#         context_data = super().get_context_data(**kwargs)
#         context_data['object_list'] = Product.objects.all()
#         return context_data


# def home(request):
#     context = {
#         'object_list': Category.objects.all(),
#         'title': 'Каталог товаров'
#     }
#     return render(request, 'catalog/product_list.html', context)

# def home(request):
#     products_list = Product.objects.all()
#     context = {
#         'object_list': products_list.all(),
#         'title': 'Главная'
#     }
#     return render(request, 'catalog/product_list.html', context)

class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product


# def products(request, pk):
#     category_name = Product.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(category=pk),
#         'title': f'Каталог товаров - {category_name.name}'
#     }
#     return render(request, 'catalog/products.html', context)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):

        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name}\nТелефон: {phone}\nСообщение: {message}')

    return render(request, 'catalog/contacts.html')


# def product(request, pk):
#     products_item = Product.objects.get(pk=pk)
#     products_list = Product.objects.filter(pk=pk)
#     context = {
#         'object_list': products_list,
#         'title': f'Продукт - {products_item}'
#     }
#     return render(request, 'catalog/product_detail.html', context)

catalog/templates/catalog/includes/inc_cur_prod.html
{% load my_tags %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <img width="200" height="300"
             class="card-img-top" src="{{ object.image|mymedia }}" alt="product">
        <div class="card-header">
            <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
            <h6 class="card-title pricing-card-title">{{ object.category }}</h6>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li class="central">{{ object.description }}</li>
                <li class="central">{{ object.created_at }}</li>
                <li class="central">{{ object.updated_at }}</li>
                {% if object.is_active %}
                <li><b>Номер версии:</b> {{ object.version_number}}</li>
                <li><b>Имя версии:</b> {{ object.version_name}}</li>
                {% endif %}
            </ul>
        </div>
        <div class="card-footer">
            <div class="btn-group">
                <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-secondary">Редактировать</a>
                <a href="{% url 'catalog:product_delete' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-danger">Удалить</a>
            </div>
        </div>
    </div>

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

catalog/templates/catalog/includes/inc_product.html
{% load my_tags %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <img width="200" height="300"
             class="card-img-top" src="{{ object.image|mymedia }}" alt="product">
        <div class="card-header">
            <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
            <h6 class="card-title pricing-card-title">{{ object.category }}</h6>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li class="central">{{ object.description|slice:100 }}</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            <a href="{% url 'catalog:product' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Информация</a>


        </div>
    </div>
</div>